name: AirPad
options:
  bundleIdPrefix: com.abdouldotdev
targets:
  AirPadClient:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources: 
      - Client
    settings:
      GENERATE_INFOPLIST_FILE: YES
      CURRENT_PROJECT_VERSION: 1
      MARKETING_VERSION: 1.0
      PRODUCT_BUNDLE_IDENTIFIER: com.abdouldotdev.AirPadClient
      SWIFT_VERSION: 5.0
      INFOPLIST_KEY_NSLocalNetworkUsageDescription: "AirPad needs local network to connect to Mac."
      INFOPLIST_KEY_NSCameraUsageDescription: "AirPad needs camera access to scan QR codes for pairing."
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES

  AirPadServer:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - Server/Sources/Server
    settings:
      GENERATE_INFOPLIST_FILE: YES
      CURRENT_PROJECT_VERSION: 1
      MARKETING_VERSION: 1.0
      PRODUCT_BUNDLE_IDENTIFIER: com.abdouldotdev.AirPadServer
      SWIFT_VERSION: 5.0
      LSUIElement: YES
